#!/bin/bash

echo "# begin build properties"
echo "# autogenerated by buildinfo.sh"

DATE="`date +%d%m%y`"

BPATH=`pwd`
BPATH2=${BPATH%/build/*}
#echo $BPATH2
#echo $TARGET_BUILD_VARIANT
SVER1=01
SVER2=13

if [ "$TARGET_BUILD_VARIANT" = "userdebug" ] ;then
	echo "ro.fota.cu_ref=F271i-Debug"
	SWVER=LYF_F271i-000-${SVER1}-${SVER2}-${DATE}_i
#	SWVER=ViLTE-eMBMS-VoWIFI-28-Nov-18_i
#	`cp -f $BPATH2/gaia/build/config/common-settings.json.debug $BPATH2/gaia/build/config/common-settings.json`
else
	echo "ro.fota.cu_ref=F271i-NBJIINB"
	SWVER=LYF_F271i-000-${SVER1}-${SVER2}-${DATE}
#	SWVER=ViLTE-eMBMS-VoWIFI-28-Nov-18
#	`cp -f $BPATH2/gaia/build/config/common-settings.json.user $BPATH2/gaia/build/config/common-settings.json`
fi

echo "ro.fota.sw_ver=${SVER1}${SVER2}"
UAS="$SWVER"


`cat $BPATH2/device/sprd/sharkle/sp9820e_2c10/default-prefs/dev-pref.js2 | sed "s#LYF-F271i#$UAS#g" \
	> $BPATH2/device/sprd/sharkle/sp9820e_2c10/default-prefs/tmp.js ;\
	mv $BPATH2/device/sprd/sharkle/sp9820e_2c10/default-prefs/tmp.js $BPATH2/device/sprd/sharkle/sp9820e_2c10/default-prefs/dev-pref.js `

echo "ro.build.id=$BUILD_ID"
echo "ro.build.display.id=$BUILD_DISPLAY_ID"
#echo "ro.build.version.incremental=$BUILD_NUMBER"
echo "ro.build.version.incremental=$SWVER"
echo "ro.build.version.sdk=$PLATFORM_SDK_VERSION"
echo "ro.build.version.preview_sdk=$PLATFORM_PREVIEW_SDK_VERSION"
echo "ro.build.version.codename=$PLATFORM_VERSION_CODENAME"
echo "ro.build.version.all_codenames=$PLATFORM_VERSION_ALL_CODENAMES"
echo "ro.build.version.release=$PLATFORM_VERSION"
echo "ro.build.version.security_patch=$PLATFORM_SECURITY_PATCH"
echo "ro.build.version.base_os=$PLATFORM_BASE_OS"
echo "ro.build.date=`date`"
echo "ro.build.date.utc=`date +%s`"
echo "ro.build.type=$TARGET_BUILD_TYPE"
echo "ro.build.user=$USER"
if test "$HOSTNAME" = ""
then
echo "ro.build.host=`hostname`"
else
echo "ro.build.host=$HOSTNAME"
fi
if [ -n "$BRANCH_BUILDTYPE" ] ; then
  echo "ro.sprd.extrainfo=$BRANCH_BUILDTYPE"
fi
echo "ro.build.tags=$BUILD_VERSION_TAGS"
echo "ro.build.flavor=$TARGET_BUILD_FLAVOR"
echo "ro.product.model=F271i"
echo "ro.product.brand=LYF"
echo "ro.product.name=F271i"
echo "ro.product.device=F271i"
echo "ro.product.board=F271i"

echo "ro.product.sar_value=Head SAR:0.809W/Kg Body SAR:0.858"

echo "ro.fota.SUMaster=fota.mst.kai.jiophone.net"
echo "ro.fota.network_type=https"
echo "ro.fota.network_port=443"


echo "ro.product.version_tag=kaios_jio_pier_2_5_20181106_R3_ER2_production"
echo "ro.product.base_version=SPRDROID6.0_KAIOS_17D_RLS1_W18.47.6"

echo "persist.user.agent=$UAS"
#echo "persist.user.agent=Mozilla/5.0 (Mobile; $UA_; Android; rv:48.0) Gecko/48.0 Firefox/48.0 KAIOS/2.5"


# These values are deprecated, use "ro.product.cpu.abilist"
# instead (see below).
echo "# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,"
echo "# use ro.product.cpu.abilist instead."
echo "ro.product.cpu.abi=$TARGET_CPU_ABI"
if [ -n "$TARGET_CPU_ABI2" ] ; then
  echo "ro.product.cpu.abi2=$TARGET_CPU_ABI2"
fi
echo "ro.product.cpu.abilist=$TARGET_CPU_ABI_LIST"
echo "ro.product.cpu.abilist32=$TARGET_CPU_ABI_LIST_32_BIT"
echo "ro.product.cpu.abilist64=$TARGET_CPU_ABI_LIST_64_BIT"

echo "ro.product.manufacturer=N"
if [ -n "$PRODUCT_DEFAULT_LOCALE" ] ; then
  echo "ro.product.locale=$PRODUCT_DEFAULT_LOCALE"
fi
echo "ro.wifi.channels=$PRODUCT_DEFAULT_WIFI_CHANNELS"
echo "ro.board.platform=$TARGET_BOARD_PLATFORM"

echo "# ro.build.product is obsolete; use ro.product.device"
echo "ro.build.product=F271i"

echo "# Do not try to parse description, fingerprint, or thumbprint"
echo "ro.build.description=$SWVER"
echo "ro.build.fingerprint=$BUILD_FINGERPRINT"
if [ -n "$BUILD_THUMBPRINT" ] ; then
  echo "ro.build.thumbprint=$BUILD_THUMBPRINT"
fi
echo "ro.build.characteristics=$TARGET_AAPT_CHARACTERISTICS"

echo "# end build properties"
